name: Run JMeter Tests

on: [push, pull_request]

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install JMeter
      run: sudo apt-get update && sudo apt-get install -y jmeter

    - name: Run JMeter tests
      run: jmeter -n -t test-plan.jmx -l results.jtl -e -o results

    - name: Notify Slack
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ JMeter tests failed in branch ${{ github.ref }}. Please check the details in the [GitHub Actions logs](${{ github.run_url }})."}' ${{ secrets.SLACK_WEBHOOK_URL }}
S