name: SonarQube Scan

on: [push, pull_request]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=SystemPedidos \
          -Dsonar.sources=.\
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Notify Slack
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ SonarQube analysis failed in branch ${{ github.ref }}. Please check the details in the [GitHub Actions logs](${{ github.run_url }})."}' ${{ secrets.SLACK_WEBHOOK_URL }}
